# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61d44cef3f362a4afce8f9d6fba7e4beda8c85b2c9189aa6a2f9ab54c31ab6c061efd1ed14f3fc7bacb5911af0f5633d73e56fe64eab1c7cb9f6795ef1bb1536

test:
  secret_key_base: cf33261fb4071e33f4180115d098f6baea438dcf0fa56cb9c871dd886bfdd3644294ec1c94053b6591d99c06e27655286fd931ad4984a553a1838f78f2634591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
